apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tyl8l5edc-python 
  janus-idp.io/tekton: tyl8l5edc-python
  backstage.io/kubernetes-id: tyl8l5edc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tyl8l5edc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  