apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tyl8l5edc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tyl8l5edc-python 
  name: tyl8l5edc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tyl8l5edc-python 
